# Generated by Django 5.0.4 on 2024-04-16 13:07

import banking.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', banking.managers.UserManager()),
            ],
        ),
    ]
