# Generated by Django 5.0.3 on 2024-03-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
